// Curated USB driver + flashing-tool catalog for the in-app Drivers center.
// Links point to the most authoritative source available; `source` labels
// whether it's a vendor-official page, the Microsoft Update Catalog, or a
// well-known community mirror so techs know what they're downloading.

export const DRIVER_CATEGORIES = ["All", "Chipset", "OEM USB", "Tools"];

export const DRIVERS = [
  // ── Chipset / flash drivers ───────────────────────────────────────────────
  {
    id: "qualcomm-9008",
    name: "Qualcomm HS-USB QDLoader 9008",
    category: "Chipset",
    platforms: ["Windows"],
    source: "MS Update Catalog",
    url: "https://www.catalog.update.microsoft.com/Search.aspx?q=qualcomm%20hs%20usb%209008",
    desc: "EDL 9008 / Sahara driver — required to flash Qualcomm devices in Emergency Download mode.",
  },
  {
    id: "mediatek-vcom",
    name: "MediaTek Preloader USB VCOM / DA",
    category: "Chipset",
    platforms: ["Windows"],
    source: "MS Update Catalog",
    url: "https://www.catalog.update.microsoft.com/Search.aspx?q=MediaTek%20VCOM",
    desc: "Preloader + SP DA VCOM ports for MT65xx / 67xx / 68xx BROM & DA flashing.",
  },
  {
    id: "spd-unisoc",
    name: "SPD / Unisoc (Spreadtrum) Driver",
    category: "Chipset",
    platforms: ["Windows"],
    source: "Community",
    url: "https://spd-flashtool.com/download/spd-driver",
    desc: "SCI-USB2Serial / SPRD download-mode driver for Spreadtrum / Unisoc chipsets.",
  },
  // ── OEM USB drivers ───────────────────────────────────────────────────────
  {
    id: "google-usb",
    name: "Google USB Driver (ADB / Fastboot)",
    category: "OEM USB",
    platforms: ["Windows"],
    source: "Official",
    url: "https://dl.google.com/android/repository/usb_driver_r13-windows.zip",
    desc: "Google's WinUSB driver for Pixel/Nexus and generic ADB & Fastboot interfaces.",
  },
  {
    id: "samsung-usb",
    name: "Samsung Android USB Driver",
    category: "OEM USB",
    platforms: ["Windows"],
    source: "Official",
    url: "https://developer.samsung.com/android-usb-driver",
    desc: "Odin / Download-mode + MTP driver for every Galaxy phone & tablet.",
  },
  {
    id: "xiaomi-usb",
    name: "Xiaomi / Mi USB Driver",
    category: "OEM USB",
    platforms: ["Windows"],
    source: "Community",
    url: "https://xiaomiflashtool.com/download/xiaomi-usb-driver",
    desc: "Mi USB + preloader driver bundled with Mi Flash (Xiaomi / Redmi / POCO).",
  },
  {
    id: "huawei-hisuite",
    name: "Huawei HiSuite (USB Driver)",
    category: "OEM USB",
    platforms: ["Windows", "macOS"],
    source: "Official",
    url: "https://consumer.huawei.com/en/support/hisuite/",
    desc: "Official Huawei / Honor suite that installs the ADB + HDB USB drivers.",
  },
  {
    id: "lg-driver",
    name: "LG United Mobile Driver",
    category: "OEM USB",
    platforms: ["Windows"],
    source: "Community",
    url: "https://lgmobiledriver.com/",
    desc: "LG download-mode (LGUP) + MTP / ADB driver.",
  },
  {
    id: "sony-companion",
    name: "Sony Xperia Companion",
    category: "OEM USB",
    platforms: ["Windows", "macOS"],
    source: "Official",
    url: "https://www.sony.com/electronics/support/downloads/W0009927",
    desc: "Xperia flashmode / fastboot driver + repair software.",
  },
  {
    id: "motorola-driver",
    name: "Motorola Device Manager",
    category: "OEM USB",
    platforms: ["Windows", "macOS"],
    source: "Community",
    url: "https://mtkdriver.com/motorola-usb-driver/",
    desc: "Motorola ADB / Fastboot + MTP driver bundle.",
  },
  {
    id: "oppo-realme",
    name: "OPPO / Realme / OnePlus Driver",
    category: "OEM USB",
    platforms: ["Windows"],
    source: "Community",
    url: "https://oppostockrom.com/oppo-usb-driver/",
    desc: "ColorOS / OxygenOS ADB + preloader (Qualcomm/MTK) driver.",
  },
  {
    id: "vivo-driver",
    name: "Vivo / iQOO USB Driver",
    category: "OEM USB",
    platforms: ["Windows"],
    source: "Community",
    url: "https://vivousbdriver.com/",
    desc: "Vivo / iQOO ADB + download-mode driver.",
  },
  // ── Tools ─────────────────────────────────────────────────────────────────
  {
    id: "platform-tools",
    name: "Android SDK Platform-Tools (adb + fastboot)",
    category: "Tools",
    platforms: ["Windows", "macOS", "Linux"],
    source: "Official",
    urls: {
      Windows: "https://dl.google.com/android/repository/platform-tools-latest-windows.zip",
      macOS: "https://dl.google.com/android/repository/platform-tools-latest-darwin.zip",
      Linux: "https://dl.google.com/android/repository/platform-tools-latest-linux.zip",
    },
    desc: "The adb & fastboot binaries — needed for `adb reboot edl`, `fastboot oem edl`, unlock, etc.",
  },
  {
    id: "zadig",
    name: "Zadig (WinUSB / libusb installer)",
    category: "Tools",
    platforms: ["Windows"],
    source: "Official",
    url: "https://zadig.akeo.ie/",
    desc: "Installs WinUSB/libusb so mtkclient / edl.py can claim BROM & EDL interfaces on Windows.",
  },
  {
    id: "libusb",
    name: "libusb",
    category: "Tools",
    platforms: ["macOS", "Linux"],
    source: "Official",
    url: "https://libusb.info/",
    desc: "Cross-platform USB library used by mtkclient / Heimdall on macOS & Linux (brew install libusb).",
  },
  {
    id: "apple-devices",
    name: "Apple Devices (Mobile Device USB Driver)",
    category: "Tools",
    platforms: ["Windows"],
    source: "Official",
    url: "https://apps.microsoft.com/detail/9np83lwlpz9k",
    desc: "Installs the Apple Mobile Device USB driver for DFU / Recovery detection on Windows.",
  },
];
